<#
  build.ps1 - Compiles PSR Clone using the .NET Framework C# compiler (csc.exe)
  that ships with every Windows installation. No SDK or runtime install required.

  Usage:
    .\build.ps1            # build
    .\build.ps1 -Run       # build then launch
    .\build.ps1 -SelfTest  # build then run the headless report self-test
    .\build.ps1 -Bump      # increment the patch version before building
    .\build.ps1 -Bump minor|major   # bump minor/major instead of patch
#>
param(
    [switch]$Run,
    [switch]$SelfTest,
    [switch]$Bump,
    [ValidateSet('major','minor','patch')]
    [string]$Part = 'patch'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$src  = Join-Path $root 'src'
$outDir = Join-Path $root 'bin'
$exe = Join-Path $outDir 'PsrClone.exe'
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# ---- Version handling (single source of truth: the VERSION file) ----
$versionFile = Join-Path $root 'VERSION'
if (-not (Test-Path $versionFile)) { '1.0.0' | Set-Content $versionFile }
$version = (Get-Content $versionFile -Raw).Trim()
if ($version -notmatch '^\d+\.\d+\.\d+$') { throw "VERSION file must be MAJOR.MINOR.PATCH, got '$version'" }

if ($Bump) {
    $p = $version.Split('.') | ForEach-Object { [int]$_ }
    switch ($Part) {
        'major' { $p[0]++; $p[1] = 0; $p[2] = 0 }
        'minor' { $p[1]++; $p[2] = 0 }
        default { $p[2]++ }
    }
    $version = "$($p[0]).$($p[1]).$($p[2])"
    $version | Set-Content $versionFile
    Write-Host "Version bumped to $version"
}
Write-Host "Version: $version"

# Generate the version source file (stamped into the assembly + BuildInfo.Version).
$verGen = Join-Path $src 'Version.g.cs'
@"
// <auto-generated> Generated by build.ps1 from the VERSION file. Do not edit. </auto-generated>
using System.Reflection;
[assembly: AssemblyVersion("$version.0")]
[assembly: AssemblyFileVersion("$version.0")]
[assembly: AssemblyInformationalVersion("$version")]
[assembly: AssemblyProduct("PSR Clone - Problem Steps Recorder replacement")]
[assembly: AssemblyTitle("PSR Clone")]
namespace PsrClone { internal static class BuildInfo { public const string Version = "$version"; } }
"@ | Set-Content -Encoding UTF8 $verGen

# Locate the newest .NET Framework 4.x csc.exe
$fwRoot = Join-Path $env:WINDIR 'Microsoft.NET\Framework64'
if (-not (Test-Path $fwRoot)) { $fwRoot = Join-Path $env:WINDIR 'Microsoft.NET\Framework' }
$csc = Get-ChildItem $fwRoot -Directory |
    Where-Object { Test-Path (Join-Path $_.FullName 'csc.exe') } |
    Sort-Object Name -Descending | Select-Object -First 1 |
    ForEach-Object { Join-Path $_.FullName 'csc.exe' }
if (-not $csc) { throw "csc.exe (.NET Framework) not found under $fwRoot" }
Write-Host "Using compiler: $csc"

# Resolve GAC assemblies for UI Automation / WindowsBase.
$gac = Join-Path $env:WINDIR 'Microsoft.NET\assembly\GAC_MSIL'
function Resolve-Gac($name) {
    $f = Get-ChildItem (Join-Path $gac $name) -Recurse -Filter "$name.dll" -ErrorAction SilentlyContinue |
         Select-Object -First 1
    if (-not $f) { throw "GAC assembly not found: $name" }
    return $f.FullName
}
$uiaClient = Resolve-Gac 'UIAutomationClient'
$uiaTypes  = Resolve-Gac 'UIAutomationTypes'
$winBase   = Resolve-Gac 'WindowsBase'

$refs = @(
    'System.dll',
    'System.Core.dll',
    'System.Drawing.dll',
    'System.Windows.Forms.dll',
    'System.Xml.dll',
    $uiaClient,
    $uiaTypes,
    $winBase
)

$sources = Get-ChildItem (Join-Path $src '*.cs') | ForEach-Object { $_.FullName }
$manifest = Join-Path $src 'app.manifest'

$refArgs = $refs | ForEach-Object { "/reference:$_" }

$cscArgs = @(
    '/nologo',
    '/target:winexe',
    '/platform:x64',
    "/out:$exe",
    "/win32manifest:$manifest",
    '/optimize+',
    '/warn:2'
) + $refArgs + $sources

Write-Host "Compiling $($sources.Count) source files..."
& $csc $cscArgs
if ($LASTEXITCODE -ne 0) { throw "Build failed (csc exit $LASTEXITCODE)" }
Write-Host "Build succeeded -> $exe"

if ($SelfTest) {
    $mht = Join-Path $outDir 'selftest.mht'
    & $exe '--selftest' $mht
    if ($LASTEXITCODE -ne 0) { throw "Self-test failed (exit $LASTEXITCODE)" }
}
if ($Run) { Start-Process $exe }
