// <auto-generated> Generated by build.ps1 from the VERSION file. Do not edit. </auto-generated>
using System.Reflection;
[assembly: AssemblyVersion("1.4.0.0")]
[assembly: AssemblyFileVersion("1.4.0.0")]
[assembly: AssemblyInformationalVersion("1.4.0")]
[assembly: AssemblyProduct("PSR Clone - Problem Steps Recorder replacement")]
[assembly: AssemblyTitle("PSR Clone")]
namespace PsrClone { internal static class BuildInfo { public const string Version = "1.4.0"; } }
